export { default as CustomerListPage } from './pages/CustomerListPage'
export { default as CustomerDetailPage } from './pages/CustomerDetailPage'
export { default as CustomerFormPage } from './pages/CustomerFormPage'
export { default as CustomerPoliciesPage } from './pages/CustomerPoliciesPage'
export { default as CustomerClaimsPage } from './pages/CustomerClaimsPage'
export { default as CustomerDocumentsPage } from './pages/CustomerDocumentsPage'
export { useCustomers } from './hooks/useCustomers'
export { useCustomerDetail } from './hooks/useCustomerDetail'
export { useCustomerForm } from './hooks/useCustomerForm'
export { useCustomerProfile } from './hooks/useCustomerProfile'
